name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ~/2025-I-IntroSciCompHPC/2025-05-14-Clase11/catch2_example

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies (g++, make, Catch2)
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ make catch2

    - name: Build with Makefile
      run: make test_factorial.x

    - name: Run tests
      run: ./test_factorial.x